FROM mariadb:10.4

#RUN groupadd -r mysql && useradd -r -g mysql mysql --home-dir /var/lib/mysql

#ENV MYSQL_DATABASE = yii
#ENV MYSQL_USER = yii
#ENV MYSQL_PASSWORD = yii
#ENV MYSQL_ROOT_PASSWORD = 12345

CMD ["mysqld"]
#COPY ../mariadb-data/ /var/lib/mariadb